apiVersion: v1
kind: Service
metadata:
  name: react-ts-rtk-bootstrap-starter
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    service: react-ts-rtk-bootstrap-starter
  type: LoadBalancer